name: Onboard Azure Account for Infoblox DNS

on:
  workflow_dispatch:
    inputs:
      subscription_id:
        description: "Azure Subscription ID"
        required: true
      infoblox_app_id:
        description: "Infoblox Application (Client) ID from Infoblox Portal"
        required: true

jobs:
  onboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install terraform

      - name: Set Terraform variables from inputs
        run: |
          echo "TF_VAR_subscription_id=${{ github.event.inputs.subscription_id }}" >> $GITHUB_ENV
          echo "TF_VAR_infoblox_app_id=${{ github.event.inputs.infoblox_app_id }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          TF_VAR_subscription_id: ${{ env.TF_VAR_subscription_id }}
          TF_VAR_infoblox_app_id: ${{ env.TF_VAR_infoblox_app_id }}
        run: terraform apply -auto-approve
