name: Onboard Azure Account for Infoblox DNS

on:
  workflow_dispatch:
    inputs:
      subscription_id:
        description: "Azure Subscription ID"
        required: true
      infoblox_app_id:
        description: "Infoblox Application (Client) ID from Infoblox Portal"
        required: true

jobs:
  onboard:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.3.5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq and Azure CLI
        run: |
          apk add --no-cache jq bash curl openssh-client ca-certificates python3 py3-pip
          pip install azure-cli

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Terraform variables from inputs
        run: |
          echo "TF_VAR_subscription_id=${{ github.event.inputs.subscription_id }}" >> $GITHUB_ENV
          echo "TF_VAR_infoblox_app_id=${{ github.event.inputs.infoblox_app_id }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply (assign custom role and create SP)
        env:
          TF_VAR_subscription_id: ${{ env.TF_VAR_subscription_id }}
          TF_VAR_infoblox_app_id: ${{ env.TF_VAR_infoblox_app_id }}
        run: terraform apply -auto-approve
